import type { MenuItem } from './types'

export const menuData: MenuItem[] = [
  // ===== VEG (Vegetarian) =====
  {
    id: 'veg-001',
    category: 'VEG',
    price: 220,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&h=400&fit=crop',
    name_mr: 'पनीर मसाला',
    name_en: 'Paneer Masala',
    description_mr: 'दाट मसाल्याच्या ग्रेव्हीमध्ये ताजा पनीर',
    description_en: 'Fresh paneer in rich masala gravy',
  },
  {
    id: 'veg-002',
    category: 'VEG',
    price: 230,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&h=400&fit=crop',
    name_mr: 'पनीर बटर मसाला',
    name_en: 'Paneer Butter Masala',
    description_mr: 'बटर आणि क्रीमयुक्त ग्रेव्हीमध्ये पनीर',
    description_en: 'Paneer in creamy butter-tomato gravy',
  },
  {
    id: 'veg-003',
    category: 'VEG',
    price: 220,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
    name_mr: 'काजू मसाला',
    name_en: 'Cashew Masala',
    description_mr: 'काजूच्या ग्रेव्हीमध्ये शिजवलेला मसाला',
    description_en: 'Rich cashew-based masala curry',
  },
  {
    id: 'veg-004',
    category: 'VEG',
    price: 250,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&h=400&fit=crop',
    name_mr: 'काजू पनीर मसाला',
    name_en: 'Cashew Paneer Masala',
    description_mr: 'काजू आणि पनीर मसाला ग्रेव्ही',
    description_en: 'Paneer in cashew-enriched masala gravy',
  },
  {
    id: 'veg-005',
    category: 'VEG',
    price: 230,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop',
    name_mr: 'पनीर चिंगारी',
    name_en: 'Paneer Chingari',
    description_mr: 'तिखट चिंगारी स्टाइल पनीर',
    description_en: 'Spicy chingari-style paneer',
  },
  {
    id: 'veg-006',
    category: 'VEG',
    price: 240,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=600&h=400&fit=crop',
    name_mr: 'पनीर चटपटा',
    name_en: 'Paneer Spicy',
    description_mr: 'तिखट चटपटा पनीर',
    description_en: 'Hot and spicy paneer preparation',
  },
  {
    id: 'veg-007',
    category: 'VEG',
    price: 250,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop',
    name_mr: 'पनीर मालवणी',
    name_en: 'Paneer Malvani',
    description_mr: 'मालवणी मसाल्यातील पनीर',
    description_en: 'Paneer in Malvani-style coconut gravy',
  },
  {
    id: 'veg-008',
    category: 'VEG',
    price: 240,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1631452180775-6b866dce4117?w=600&h=400&fit=crop',
    name_mr: 'पनीर तुफानी',
    name_en: 'Cheese Storm',
    description_mr: 'पनीर तुफानी स्पेशल',
    description_en: 'Cheese-loaded storm special',
  },
  {
    id: 'veg-009',
    category: 'VEG',
    price: 250,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1505253758473-96b7015fcd40?w=600&h=400&fit=crop',
    name_mr: 'काजू पनीर तुफानी',
    name_en: 'Cashew Cheese Storm',
    description_mr: 'काजू पनीर तुफानी स्पेशल',
    description_en: 'Cashew and cheese storm special',
  },
  {
    id: 'veg-010',
    category: 'VEG',
    price: 200,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&h=400&fit=crop',
    name_mr: 'शाकाहारी थाळी',
    name_en: 'Vegetarian Plate',
    description_mr: 'संपूर्ण शाकाहारी थाळी',
    description_en: 'Complete vegetarian plate',
  },
  {
    id: 'veg-011',
    category: 'VEG',
    price: 160,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&h=400&fit=crop',
    name_mr: 'मिक्स वेज',
    name_en: 'Mix Veg',
    description_mr: 'मिश्र भाज्यांची भाजी',
    description_en: 'Mixed vegetable curry',
  },
  {
    id: 'veg-012',
    category: 'VEG',
    price: 180,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&h=400&fit=crop',
    name_mr: 'वेज कोल्हापुरी',
    name_en: 'Veg Kolhapuri',
    description_mr: 'कोल्हापुरी मसाल्यातील भाज्या',
    description_en: 'Vegetables in spicy Kolhapuri masala',
  },
  {
    id: 'veg-013',
    category: 'VEG',
    price: 220,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?w=600&h=400&fit=crop',
    name_mr: 'वेज मालवणी',
    name_en: 'Veg Malvani',
    description_mr: 'मालवणी स्टाइल भाज्या',
    description_en: 'Vegetables in Malvani-style gravy',
  },
  {
    id: 'veg-014',
    category: 'VEG',
    price: 120,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=600&h=400&fit=crop',
    name_mr: 'डाळ तडका',
    name_en: 'Dal Tadka',
    description_mr: 'तडका दिलेली डाळ',
    description_en: 'Tempered lentil dal',
  },
  {
    id: 'veg-015',
    category: 'VEG',
    price: 100,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
    name_mr: 'डाळ फ्राय',
    name_en: 'Dal Fry',
    description_mr: 'फ्राय केलेली डाळ',
    description_en: 'Fried lentil dal',
  },

  // ===== NON-VEG PLATTER =====
  {
    id: 'nvp-001',
    category: 'NON_VEG_PLATTER',
    price: 180,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
    name_mr: 'चिकन मसाला थाळी',
    name_en: 'Chicken Masala Thali',
    description_mr: 'चिकन मसाला थाळी',
    description_en: 'Chicken masala thali with rice and roti',
  },
  {
    id: 'nvp-002',
    category: 'NON_VEG_PLATTER',
    price: 180,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&h=400&fit=crop',
    name_mr: 'चिकन धनगरी थाळी',
    name_en: 'Chicken Dhangari Thali',
    description_mr: 'चिकन धनगरी थाळी',
    description_en: 'Chicken dhangari thali',
  },
  {
    id: 'nvp-003',
    category: 'NON_VEG_PLATTER',
    price: 180,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&h=400&fit=crop',
    name_mr: 'चिकन मालवणी थाळी',
    name_en: 'Chicken Malvani Thali',
    description_mr: 'चिकन मालवणी थाळी',
    description_en: 'Chicken Malvani-style thali',
  },
  {
    id: 'nvp-004',
    category: 'NON_VEG_PLATTER',
    price: 180,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&h=400&fit=crop',
    name_mr: 'चिकन आळणी थाळी',
    name_en: 'Chicken Aalani Thali',
    description_mr: 'चिकन आळणी थाळी',
    description_en: 'Chicken aalani thali',
  },
  {
    id: 'nvp-005',
    category: 'NON_VEG_PLATTER',
    price: 250,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&h=400&fit=crop',
    name_mr: 'चिकन स्पेशल थाळी',
    name_en: 'Chicken Special Thali',
    description_mr: 'चिकन स्पेशल थाळी',
    description_en: 'Special chicken thali with extras',
  },
  {
    id: 'nvp-006',
    category: 'NON_VEG_PLATTER',
    price: 250,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=400&fit=crop',
    name_mr: 'चिकन गावरान थाळी',
    name_en: 'Chicken Gavran Thali',
    description_mr: 'गावरान चिकन थाळी',
    description_en: 'Country chicken (gavran) thali',
  },
  {
    id: 'nvp-007',
    category: 'NON_VEG_PLATTER',
    price: 300,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1606491956689-2ea866880049?w=600&h=400&fit=crop',
    name_mr: 'चिकन गावरान',
    name_en: 'Chicken Gavran',
    description_mr: 'गावरान चिकन',
    description_en: 'Country chicken (gavran) curry',
  },
  {
    id: 'nvp-008',
    category: 'NON_VEG_PLATTER',
    price: 300,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1642821373181-696a54913e93?w=600&h=400&fit=crop',
    name_mr: 'स्पेशल प्लेट',
    name_en: 'Special Plate',
    description_mr: 'स्पेशल नॉन-व्हेज प्लेट',
    description_en: 'Special non-veg plate',
  },

  // ===== CHICKEN HANDI =====
  {
    id: 'ch-001',
    category: 'CHICKEN_HANDI',
    price: 330,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&h=400&fit=crop',
    name_mr: 'चिकन हंडी (हाफ)',
    name_en: 'Chicken Handi (Half)',
    description_mr: 'हंडीमध्ये शिजवलेले चिकन - हाफ',
    description_en: 'Chicken cooked in handi - half portion',
  },
  {
    id: 'ch-002',
    category: 'CHICKEN_HANDI',
    price: 650,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&h=400&fit=crop',
    name_mr: 'चिकन हंडी (फुल)',
    name_en: 'Chicken Handi (Full)',
    description_mr: 'हंडीमध्ये शिजवलेले चिकन - फुल',
    description_en: 'Chicken cooked in handi - full portion',
  },
  {
    id: 'ch-003',
    category: 'CHICKEN_HANDI',
    price: 330,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1606491956689-2ea866880049?w=600&h=400&fit=crop',
    name_mr: 'चिकन मालवणी हंडी (हाफ)',
    name_en: 'Chicken Malvani Handi (Half)',
    description_mr: 'मालवणी स्टाइल चिकन हंडी - हाफ',
    description_en: 'Malvani-style chicken handi - half',
  },
  {
    id: 'ch-004',
    category: 'CHICKEN_HANDI',
    price: 650,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&h=400&fit=crop',
    name_mr: 'चिकन मालवणी हंडी (फुल)',
    name_en: 'Chicken Malvani Handi (Full)',
    description_mr: 'मालवणी स्टाइल चिकन हंडी - फुल',
    description_en: 'Malvani-style chicken handi - full',
  },
  {
    id: 'ch-005',
    category: 'CHICKEN_HANDI',
    price: 330,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=400&fit=crop',
    name_mr: 'चिकन घरगुती हंडी (हाफ)',
    name_en: 'Chicken Homemade Handi (Half)',
    description_mr: 'घरगुती स्टाइल चिकन हंडी - हाफ',
    description_en: 'Homemade-style chicken handi - half',
  },
  {
    id: 'ch-006',
    category: 'CHICKEN_HANDI',
    price: 650,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1642821373181-696a54913e93?w=600&h=400&fit=crop',
    name_mr: 'चिकन घरगुती हंडी (फुल)',
    name_en: 'Chicken Homemade Handi (Full)',
    description_mr: 'घरगुती स्टाइल चिकन हंडी - फुल',
    description_en: 'Homemade-style chicken handi - full',
  },
  {
    id: 'ch-007',
    category: 'CHICKEN_HANDI',
    price: 320,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
    name_mr: 'चिकन धनगरी हंडी (हाफ)',
    name_en: 'Chicken Dhangari Handi (Half)',
    description_mr: 'धनगरी स्टाइल चिकन हंडी - हाफ',
    description_en: 'Dhangari-style chicken handi - half',
  },
  {
    id: 'ch-008',
    category: 'CHICKEN_HANDI',
    price: 630,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1606491956689-2ea866880049?w=600&h=400&fit=crop',
    name_mr: 'चिकन धनगरी हंडी (फुल)',
    name_en: 'Chicken Dhangari Handi (Full)',
    description_mr: 'धनगरी स्टाइल चिकन हंडी - फुल',
    description_en: 'Dhangari-style chicken handi - full',
  },
  {
    id: 'ch-009',
    category: 'CHICKEN_HANDI',
    price: 320,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&h=400&fit=crop',
    name_mr: 'चिकन कोल्हापुरी हंडी (हाफ)',
    name_en: 'Chicken Kolhapuri Handi (Half)',
    description_mr: 'कोल्हापुरी स्टाइल चिकन हंडी - हाफ',
    description_en: 'Kolhapuri-style chicken handi - half',
  },
  {
    id: 'ch-010',
    category: 'CHICKEN_HANDI',
    price: 630,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&h=400&fit=crop',
    name_mr: 'चिकन कोल्हापुरी हंडी (फुल)',
    name_en: 'Chicken Kolhapuri Handi (Full)',
    description_mr: 'कोल्हापुरी स्टाइल चिकन हंडी - फुल',
    description_en: 'Kolhapuri-style chicken handi - full',
  },
  {
    id: 'ch-011',
    category: 'CHICKEN_HANDI',
    price: 450,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&h=400&fit=crop',
    name_mr: 'चिकन गावरान हंडी (हाफ)',
    name_en: 'Chicken Gavran Handi (Half)',
    description_mr: 'गावरान चिकन हंडी - हाफ',
    description_en: 'Country chicken handi - half',
  },
  {
    id: 'ch-012',
    category: 'CHICKEN_HANDI',
    price: 800,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=400&fit=crop',
    name_mr: 'चिकन गावरान हंडी (फुल)',
    name_en: 'Chicken Gavran Handi (Full)',
    description_mr: 'गावरान चिकन हंडी - फुल',
    description_en: 'Country chicken handi - full',
  },

  // ===== MUTTON HANDI =====
  {
    id: 'mh-001',
    category: 'MUTTON_HANDI',
    price: 600,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&h=400&fit=crop',
    name_mr: 'मटण हंडी (हाफ)',
    name_en: 'Mutton Handi (Half)',
    description_mr: 'हंडीमध्ये शिजवलेले मटण - हाफ',
    description_en: 'Mutton cooked in handi - half portion',
  },
  {
    id: 'mh-002',
    category: 'MUTTON_HANDI',
    price: 1150,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=600&h=400&fit=crop',
    name_mr: 'मटण हंडी (फुल)',
    name_en: 'Mutton Handi (Full)',
    description_mr: 'हंडीमध्ये शिजवलेले मटण - फुल',
    description_en: 'Mutton cooked in handi - full portion',
  },
  {
    id: 'mh-003',
    category: 'MUTTON_HANDI',
    price: 600,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1606491956689-2ea866880049?w=600&h=400&fit=crop',
    name_mr: 'मटण मालवणी हंडी (हाफ)',
    name_en: 'Mutton Malvani Handi (Half)',
    description_mr: 'मालवणी स्टाइल मटण हंडी - हाफ',
    description_en: 'Malvani-style mutton handi - half',
  },
  {
    id: 'mh-004',
    category: 'MUTTON_HANDI',
    price: 1150,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&h=400&fit=crop',
    name_mr: 'मटण मालवणी हंडी (फुल)',
    name_en: 'Mutton Malvani Handi (Full)',
    description_mr: 'मालवणी स्टाइल मटण हंडी - फुल',
    description_en: 'Malvani-style mutton handi - full',
  },
  {
    id: 'mh-005',
    category: 'MUTTON_HANDI',
    price: 600,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=600&h=400&fit=crop',
    name_mr: 'मटण घरगुती हंडी (हाफ)',
    name_en: 'Mutton Homemade Handi (Half)',
    description_mr: 'घरगुती स्टाइल मटण हंडी - हाफ',
    description_en: 'Homemade-style mutton handi - half',
  },
  {
    id: 'mh-006',
    category: 'MUTTON_HANDI',
    price: 1150,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1606491956689-2ea866880049?w=600&h=400&fit=crop',
    name_mr: 'मटण घरगुती हंडी (फुल)',
    name_en: 'Mutton Homemade Handi (Full)',
    description_mr: 'घरगुती स्टाइल मटण हंडी - फुल',
    description_en: 'Homemade-style mutton handi - full',
  },
  {
    id: 'mh-007',
    category: 'MUTTON_HANDI',
    price: 600,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&h=400&fit=crop',
    name_mr: 'मटण धनगरी हंडी (हाफ)',
    name_en: 'Mutton Dhangari Handi (Half)',
    description_mr: 'धनगरी स्टाइल मटण हंडी - हाफ',
    description_en: 'Dhangari-style mutton handi - half',
  },
  {
    id: 'mh-008',
    category: 'MUTTON_HANDI',
    price: 1150,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=600&h=400&fit=crop',
    name_mr: 'मटण धनगरी हंडी (फुल)',
    name_en: 'Mutton Dhangari Handi (Full)',
    description_mr: 'धनगरी स्टाइल मटण हंडी - फुल',
    description_en: 'Dhangari-style mutton handi - full',
  },
  {
    id: 'mh-009',
    category: 'MUTTON_HANDI',
    price: 600,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1606491956689-2ea866880049?w=600&h=400&fit=crop',
    name_mr: 'मटण कोल्हापुरी हंडी (हाफ)',
    name_en: 'Mutton Kolhapuri Handi (Half)',
    description_mr: 'कोल्हापुरी स्टाइल मटण हंडी - हाफ',
    description_en: 'Kolhapuri-style mutton handi - half',
  },
  {
    id: 'mh-010',
    category: 'MUTTON_HANDI',
    price: 1150,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&h=400&fit=crop',
    name_mr: 'मटण कोल्हापुरी हंडी (फुल)',
    name_en: 'Mutton Kolhapuri Handi (Full)',
    description_mr: 'कोल्हापुरी स्टाइल मटण हंडी - फुल',
    description_en: 'Kolhapuri-style mutton handi - full',
  },

  // ===== MUTTON PLATE =====
  {
    id: 'mp-001',
    category: 'MUTTON_PLATE',
    price: 300,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=600&h=400&fit=crop',
    name_mr: 'मटण मसाला थाळी',
    name_en: 'Mutton Masala Thali',
    description_mr: 'मटण मसाला थाळी',
    description_en: 'Mutton masala thali with rice and roti',
  },
  {
    id: 'mp-002',
    category: 'MUTTON_PLATE',
    price: 300,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&h=400&fit=crop',
    name_mr: 'मटण मालवणी थाळी',
    name_en: 'Mutton Malvani Thali',
    description_mr: 'मटण मालवणी थाळी',
    description_en: 'Mutton Malvani-style thali',
  },
  {
    id: 'mp-003',
    category: 'MUTTON_PLATE',
    price: 300,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1606491956689-2ea866880049?w=600&h=400&fit=crop',
    name_mr: 'मटण घरगुती थाळी',
    name_en: 'Mutton Homemade Thali',
    description_mr: 'घरगुती स्टाइल मटण थाळी',
    description_en: 'Homemade-style mutton thali',
  },
  {
    id: 'mp-004',
    category: 'MUTTON_PLATE',
    price: 300,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=600&h=400&fit=crop',
    name_mr: 'मटण धनगरी थाळी',
    name_en: 'Mutton Dhangari Thali',
    description_mr: 'मटण धनगरी थाळी',
    description_en: 'Mutton dhangari thali',
  },
  {
    id: 'mp-005',
    category: 'MUTTON_PLATE',
    price: 350,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=600&h=400&fit=crop',
    name_mr: 'मटण स्पेशल थाळा',
    name_en: 'Mutton Special Thali',
    description_mr: 'मटण स्पेशल थाळा',
    description_en: 'Special mutton thali with extras',
  },
  {
    id: 'mp-006',
    category: 'MUTTON_PLATE',
    price: 300,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1606491956689-2ea866880049?w=600&h=400&fit=crop',
    name_mr: 'मटण आळणी थाळी',
    name_en: 'Mutton Aalani Thali',
    description_mr: 'मटण आळणी थाळी',
    description_en: 'Mutton aalani thali',
  },
  {
    id: 'mp-007',
    category: 'MUTTON_PLATE',
    price: 200,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=600&h=400&fit=crop',
    name_mr: 'वजडी थाळी',
    name_en: 'Wajadi Plate',
    description_mr: 'वजडी थाळी',
    description_en: 'Wajadi plate',
  },

  // ===== EGG =====
  {
    id: 'egg-001',
    category: 'EGG',
    price: 150,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600&h=400&fit=crop',
    name_mr: 'अंडा मसाला थाळी',
    name_en: 'Egg Masala Platter',
    description_mr: 'अंडा मसाला थाळी',
    description_en: 'Egg masala platter',
  },
  {
    id: 'egg-002',
    category: 'EGG',
    price: 140,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&h=400&fit=crop',
    name_mr: 'अंडा करी थाळी',
    name_en: 'Egg Curry Plate',
    description_mr: 'अंडा करी थाळी',
    description_en: 'Egg curry plate',
  },
  {
    id: 'egg-003',
    category: 'EGG',
    price: 170,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600&h=400&fit=crop',
    name_mr: 'अंडा मख्खनवाला थाळी',
    name_en: 'Egg and Butter Platter',
    description_mr: 'अंडा मख्खनवाला थाळी',
    description_en: 'Egg and butter platter',
  },
  {
    id: 'egg-004',
    category: 'EGG',
    price: 150,
    is_veg: false,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&h=400&fit=crop',
    name_mr: 'अंडा धनगरी थाळी',
    name_en: 'Egg Dhangari Thali',
    description_mr: 'अंडा धनगरी थाळी',
    description_en: 'Egg dhangari thali',
  },

  // ===== RICE =====
  {
    id: 'rice-001',
    category: 'RICE',
    price: 60,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=600&h=400&fit=crop',
    name_mr: 'प्लेन राईस (हाफ)',
    name_en: 'Plain Rice (Half)',
    description_mr: 'साधा वाफवलेला भात - हाफ',
    description_en: 'Steamed plain rice - half portion',
  },
  {
    id: 'rice-002',
    category: 'RICE',
    price: 120,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=600&h=400&fit=crop',
    name_mr: 'प्लेन राईस (फुल)',
    name_en: 'Plain Rice (Full)',
    description_mr: 'साधा वाफवलेला भात - फुल',
    description_en: 'Steamed plain rice - full portion',
  },
  {
    id: 'rice-003',
    category: 'RICE',
    price: 70,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=600&h=400&fit=crop',
    name_mr: 'जरा राईस (हाफ)',
    name_en: 'A Little Rice (Half)',
    description_mr: 'थोडा भात - हाफ',
    description_en: 'Small rice portion - half',
  },
  {
    id: 'rice-004',
    category: 'RICE',
    price: 130,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=600&h=400&fit=crop',
    name_mr: 'जरा राईस (फुल)',
    name_en: 'A Little Rice (Full)',
    description_mr: 'थोडा भात - फुल',
    description_en: 'Small rice portion - full',
  },
  {
    id: 'rice-005',
    category: 'RICE',
    price: 200,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
    name_mr: 'डाळ खिचडी',
    name_en: 'Dal Khichdi',
    description_mr: 'डाळ खिचडी',
    description_en: 'Dal khichdi',
  },

  // ===== BREAD =====
  {
    id: 'bread-001',
    category: 'BREAD',
    price: 20,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop',
    name_mr: 'प्लेन रोटी',
    name_en: 'Plain Roti',
    description_mr: 'प्लेन रोटी',
    description_en: 'Plain tandoor roti',
  },
  {
    id: 'bread-002',
    category: 'BREAD',
    price: 30,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?w=600&h=400&fit=crop',
    name_mr: 'बटर रोटी',
    name_en: 'Butter Roti',
    description_mr: 'बटर लावलेली रोटी',
    description_en: 'Butter roti',
  },
  {
    id: 'bread-003',
    category: 'BREAD',
    price: 20,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop',
    name_mr: 'भाकरी',
    name_en: 'Bhakri',
    description_mr: 'भाकरी',
    description_en: 'Bhakri',
  },
  {
    id: 'bread-004',
    category: 'BREAD',
    price: 20,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?w=600&h=400&fit=crop',
    name_mr: 'चपाती',
    name_en: 'Chapati',
    description_mr: 'चपाती',
    description_en: 'Chapati',
  },
  {
    id: 'bread-005',
    category: 'BREAD',
    price: 20,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop',
    name_mr: 'पराठा',
    name_en: 'Parata',
    description_mr: 'पराठा',
    description_en: 'Parata',
  },

  // ===== OTHERS =====
  {
    id: 'oth-001',
    category: 'OTHERS',
    price: 40,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&h=400&fit=crop',
    name_mr: 'पापड',
    name_en: 'Papad',
    description_mr: 'पापड',
    description_en: 'Papad',
  },
  {
    id: 'oth-002',
    category: 'OTHERS',
    price: 30,
    is_veg: true,
    is_available: true,
    image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&h=400&fit=crop',
    name_mr: 'फ्राय पापड',
    name_en: 'Fry Papad',
    description_mr: 'फ्राय पापड',
    description_en: 'Fried papad',
  },
]
